spring:
  application:
    name: order-service
  rabbitmq:
    addresses: mosquito-01.rmq.cloudamqp.com
    username: fufuyotz
    password: vQTYy7Bcm_vuIugYdClr-YWuiqRm4L_9

#    host: localhost
#    port: 5672
#    addresses: localhost:5672
#    username: guest
#    password: guest

server:
  port: 2222
  context-path: /order-service
  error:
    whitelabel:
      enabled: false

management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false

eureka:
  instance:
    lease-expiration-duration-in-seconds: 2 
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://localhost:8761/eureka/}
      #defaultZone: http://localhost:8761/eureka/
      

demoone:
  rabbitmq:
      exchange: demo.exchange
      queue: demo.queue
      routingkey: demo.routingkey
      
#rabbit:
#  connection-url: ${vcap.services.rabbit-mq.credentials.uri:localRabbit}

